name: Deploy NGINX Ingress to k8s
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy NGINX Ingress to k8s
    steps:
      - uses: actions/checkout@v1
      - name: Configure AKS context
        uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: testcluster
          resource-group: testspring
      - name: Deploy rolling update to AKS cluster
        uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            manifests/ns-and-sa.yaml
            manifests/rbac.yaml
            manifests/default-server-secret.yaml
            manifests/nginx-config.yaml
            manifests/custom-resource-definitions.yaml
            manifests/nginx-ingress.yaml
